# action.yml
name: 'Nova Labs Rust Cargo Deb Package Build (amd64, Ubuntu)'
description: 'Builds a statically linked .deb package, amd64, musl, ubuntu'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  toml_path:
    description: 'Relative path to Cargo.toml'
    required: true
  cmd:
    description: 'build command'
    required: true
    default: 'cargo deb --target=x86_64-unknown-linux-musl'
runs:
  using: 'docker'
  image: 'Dockerfile'
  #image: 'docker://quay.io/team-helium/cargo-deb-amd64-ubuntu:1.1'
  args:
    - ${{ inputs.cmd }}
